/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.CategoryController;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author DELL
 */
public class CategoryView extends javax.swing.JPanel {
    private CategoryController categoryController;
    public CategoryView() {
        initComponents();
        categoryController=new CategoryController(this);
        this.deshabilitarBotones();
        categoryController.showCategory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipalC = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCategories = new javax.swing.JTable(){
            public boolean isCellEditable(int i, int j){
                return false;
            }
        };
        btnBorrarCat = new javax.swing.JButton();
        lblCategory = new javax.swing.JLabel();
        btnAgregarCat = new javax.swing.JButton();
        btnActualizarCat = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        setLayout(new java.awt.CardLayout());

        tableCategories.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableCategories.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCategoriesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableCategories);

        btnBorrarCat.setText("Eliminar");
        btnBorrarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarCatActionPerformed(evt);
            }
        });

        lblCategory.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCategory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCategory.setText("CATEGORIAS");

        btnAgregarCat.setText("Agregar");
        btnAgregarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCatActionPerformed(evt);
            }
        });

        btnActualizarCat.setText("Cambiar nombre");
        btnActualizarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarCatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalCLayout = new javax.swing.GroupLayout(panelPrincipalC);
        panelPrincipalC.setLayout(panelPrincipalCLayout);
        panelPrincipalCLayout.setHorizontalGroup(
            panelPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalCLayout.createSequentialGroup()
                .addGroup(panelPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCategory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelPrincipalCLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalCLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(btnAgregarCat)
                        .addGap(73, 73, 73)
                        .addComponent(btnActualizarCat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBorrarCat)
                        .addGap(68, 68, 68)))
                .addContainerGap())
        );
        panelPrincipalCLayout.setVerticalGroup(
            panelPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalCLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBorrarCat, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(btnAgregarCat, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(btnActualizarCat, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(panelPrincipalC, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btnBorrarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarCatActionPerformed
        categoryController.DeleteCategory(evt);
    }//GEN-LAST:event_btnBorrarCatActionPerformed

    private void tableCategoriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCategoriesMouseClicked
        categoryController.TableMouseClicked(evt);
    }//GEN-LAST:event_tableCategoriesMouseClicked

    private void btnAgregarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarCatActionPerformed

    private void btnActualizarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarCatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarCat;
    private javax.swing.JButton btnAgregarCat;
    private javax.swing.JButton btnBorrarCat;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JPanel panelPrincipalC;
    private javax.swing.JTable tableCategories;
    // End of variables declaration//GEN-END:variables
    //METODO PARA LLENAR EL COMBOBOX
    /*public void itemsComboTiposHab(ArrayList<String> listItems){
        this.comboItems.removeAllItems();
        this.comboItems.addItem("");
        for(String l : listItems){
            this.comboItems.addItem(l);
        }
        this.jPanel2.updateUI();
    }*/
    
    public void deshabilitarBotones(){
        this.btnBorrarCat.setEnabled(false);
        this.btnActualizarCat.setEnabled(false);
    }
    
    public void habilitarBotones(){
        this.btnBorrarCat.setEnabled(true);
        this.btnActualizarCat.setEnabled(true);
    }

    public CategoryController getCategoryController() {
        return categoryController;
    }

    public void setCategoryController(CategoryController categoryController) {
        this.categoryController = categoryController;
    }

    public JButton getBtnActualizarCat() {
        return btnActualizarCat;
    }

    public void setBtnActualizarCat(JButton btnActualizarCat) {
        this.btnActualizarCat = btnActualizarCat;
    }

    public JButton getBtnAgregarCat() {
        return btnAgregarCat;
    }

    public void setBtnAgregarCat(JButton btnAgregarCat) {
        this.btnAgregarCat = btnAgregarCat;
    }

    public JButton getBtnBorrarCat() {
        return btnBorrarCat;
    }

    public void setBtnBorrarCat(JButton btnBorrarCat) {
        this.btnBorrarCat = btnBorrarCat;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JLabel getLblCategory() {
        return lblCategory;
    }

    public void setLblCategory(JLabel lblCategory) {
        this.lblCategory = lblCategory;
    }

    public JPanel getPanelPrincipalC() {
        return panelPrincipalC;
    }

    public void setPanelPrincipalC(JPanel panelPrincipalC) {
        this.panelPrincipalC = panelPrincipalC;
    }

    public JTable getTableCategories() {
        return tableCategories;
    }

    public void setTableCategories(JTable tableCategories) {
        this.tableCategories = tableCategories;
    }
    
    
    
}
