/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.CategoryController;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author DELL
 */
public class CategoryView extends javax.swing.JPanel {
    private CategoryController categoryController;
    public CategoryView() {
        initComponents();
        categoryController=new CategoryController(this);
        this.deshabilitarBotones();
        categoryController.showCategory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipalC = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCategories = new javax.swing.JTable(){
            public boolean isCellEditable(int i, int j){
                return false;
            }
        };
        btnBorrarCat = new javax.swing.JButton();
        lblCategory = new javax.swing.JLabel();
        btnAgregarCat = new javax.swing.JButton();
        btnActualizarCat = new javax.swing.JButton();
        btnUndo = new javax.swing.JButton();
        btnRedo = new javax.swing.JButton();
        panelAgregarC = new javax.swing.JPanel();
        lblCategory1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombreAgregar = new javax.swing.JTextField();
        btnCancelarAC = new javax.swing.JButton();
        btnAgregarC = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        setLayout(new java.awt.CardLayout());

        tableCategories.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableCategories.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCategoriesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableCategories);

        btnBorrarCat.setText("Eliminar");
        btnBorrarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarCatActionPerformed(evt);
            }
        });

        lblCategory.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCategory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCategory.setText("CATEGORIAS");

        btnAgregarCat.setText("Agregar");
        btnAgregarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCatActionPerformed(evt);
            }
        });

        btnActualizarCat.setText("Cambiar nombre");
        btnActualizarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarCatActionPerformed(evt);
            }
        });

        btnUndo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Arrows-Undo-icon.png"))); // NOI18N

        btnRedo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Arrows-Redo-icon.png"))); // NOI18N

        javax.swing.GroupLayout panelPrincipalCLayout = new javax.swing.GroupLayout(panelPrincipalC);
        panelPrincipalC.setLayout(panelPrincipalCLayout);
        panelPrincipalCLayout.setHorizontalGroup(
            panelPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalCLayout.createSequentialGroup()
                .addGroup(panelPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCategory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelPrincipalCLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalCLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnAgregarCat)
                        .addGap(29, 29, 29)
                        .addComponent(btnActualizarCat)
                        .addGap(29, 29, 29)
                        .addComponent(btnBorrarCat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUndo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRedo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)))
                .addContainerGap())
        );
        panelPrincipalCLayout.setVerticalGroup(
            panelPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalCLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBorrarCat, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                        .addComponent(btnAgregarCat, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                        .addComponent(btnActualizarCat, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                    .addGroup(panelPrincipalCLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUndo)
                            .addComponent(btnRedo))))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(panelPrincipalC, "card2");

        lblCategory1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCategory1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCategory1.setText("CATEGORIA");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nombre");

        btnCancelarAC.setText("Cancelar");
        btnCancelarAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarACActionPerformed(evt);
            }
        });

        btnAgregarC.setText("Agregar");
        btnAgregarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAgregarCLayout = new javax.swing.GroupLayout(panelAgregarC);
        panelAgregarC.setLayout(panelAgregarCLayout);
        panelAgregarCLayout.setHorizontalGroup(
            panelAgregarCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCategory1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAgregarCLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelAgregarCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAgregarCLayout.createSequentialGroup()
                        .addComponent(btnAgregarC, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnCancelarAC, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(167, 167, 167))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAgregarCLayout.createSequentialGroup()
                        .addGroup(panelAgregarCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAgregarCLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel3))
                            .addComponent(txtNombreAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(206, 206, 206))))
        );
        panelAgregarCLayout.setVerticalGroup(
            panelAgregarCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarCLayout.createSequentialGroup()
                .addComponent(lblCategory1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(panelAgregarCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarC, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarAC, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        add(panelAgregarC, "card3");
    }// </editor-fold>//GEN-END:initComponents

    private void btnBorrarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarCatActionPerformed
        categoryController.ActionPerformed(evt);
    }//GEN-LAST:event_btnBorrarCatActionPerformed

    private void tableCategoriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCategoriesMouseClicked
        categoryController.TableMouseClicked(evt);
    }//GEN-LAST:event_tableCategoriesMouseClicked

    private void btnAgregarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCatActionPerformed
        categoryController.ActionPerformed(evt);
    }//GEN-LAST:event_btnAgregarCatActionPerformed

    private void btnActualizarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarCatActionPerformed
        categoryController.ActionPerformed(evt);
    }//GEN-LAST:event_btnActualizarCatActionPerformed

    private void btnAgregarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCActionPerformed
        categoryController.ActionPerformed(evt);
    }//GEN-LAST:event_btnAgregarCActionPerformed

    private void btnCancelarACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarACActionPerformed
        categoryController.ActionPerformed(evt);
    }//GEN-LAST:event_btnCancelarACActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarCat;
    private javax.swing.JButton btnAgregarC;
    private javax.swing.JButton btnAgregarCat;
    private javax.swing.JButton btnBorrarCat;
    private javax.swing.JButton btnCancelarAC;
    private javax.swing.JButton btnRedo;
    private javax.swing.JButton btnUndo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblCategory1;
    private javax.swing.JPanel panelAgregarC;
    private javax.swing.JPanel panelPrincipalC;
    private javax.swing.JTable tableCategories;
    private javax.swing.JTextField txtNombreAgregar;
    // End of variables declaration//GEN-END:variables
    public void habilitarPanelAgregar(){
        this.panelAgregarC.setVisible(true);
        this.panelPrincipalC.setVisible(false);
    }
    
    public void habilitarPanelCategoria(){
        this.panelAgregarC.setVisible(false);
        this.panelPrincipalC.setVisible(true);
    }
    
    public void deshabilitarBotones(){
        this.btnBorrarCat.setEnabled(false);
        this.btnActualizarCat.setEnabled(false);
        this.btnRedo.setEnabled(false);
        this.btnUndo.setEnabled(false);
    }
    
    public void habilitarBotones(){
        this.btnBorrarCat.setEnabled(true);
        this.btnActualizarCat.setEnabled(true);
    }

    public CategoryController getCategoryController() {
        return categoryController;
    }

    public void setCategoryController(CategoryController categoryController) {
        this.categoryController = categoryController;
    }

    public JButton getBtnActualizarCat() {
        return btnActualizarCat;
    }

    public void setBtnActualizarCat(JButton btnActualizarCat) {
        this.btnActualizarCat = btnActualizarCat;
    }

    public JButton getBtnAgregarC() {
        return btnAgregarC;
    }

    public void setBtnAgregarC(JButton btnAgregarC) {
        this.btnAgregarC = btnAgregarC;
    }

    public JButton getBtnAgregarCat() {
        return btnAgregarCat;
    }

    public void setBtnAgregarCat(JButton btnAgregarCat) {
        this.btnAgregarCat = btnAgregarCat;
    }

    public JButton getBtnBorrarCat() {
        return btnBorrarCat;
    }

    public void setBtnBorrarCat(JButton btnBorrarCat) {
        this.btnBorrarCat = btnBorrarCat;
    }

    public JButton getBtnCancelarAC() {
        return btnCancelarAC;
    }

    public void setBtnCancelarAC(JButton btnCancelarAC) {
        this.btnCancelarAC = btnCancelarAC;
    }

    public JButton getBtnRedo() {
        return btnRedo;
    }

    public void setBtnRedo(JButton btnRedo) {
        this.btnRedo = btnRedo;
    }

    public JButton getBtnUndo() {
        return btnUndo;
    }

    public void setBtnUndo(JButton btnUndo) {
        this.btnUndo = btnUndo;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JLabel getLblCategory() {
        return lblCategory;
    }

    public void setLblCategory(JLabel lblCategory) {
        this.lblCategory = lblCategory;
    }

    public JLabel getLblCategory1() {
        return lblCategory1;
    }

    public void setLblCategory1(JLabel lblCategory1) {
        this.lblCategory1 = lblCategory1;
    }

    public JPanel getPanelAgregarC() {
        return panelAgregarC;
    }

    public void setPanelAgregarC(JPanel panelAgregarC) {
        this.panelAgregarC = panelAgregarC;
    }

    public JPanel getPanelPrincipalC() {
        return panelPrincipalC;
    }

    public void setPanelPrincipalC(JPanel panelPrincipalC) {
        this.panelPrincipalC = panelPrincipalC;
    }

    public JTable getTableCategories() {
        return tableCategories;
    }

    public void setTableCategories(JTable tableCategories) {
        this.tableCategories = tableCategories;
    }

    public JTextField getTxtNombreAgregar() {
        return txtNombreAgregar;
    }

    public void setTxtNombreAgregar(JTextField txtNombreAgregar) {
        this.txtNombreAgregar = txtNombreAgregar;
    }

    public void cleanFieldsAgregar() {
        this.txtNombreAgregar.setText("");
    }

    
    
    
}
