/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.DebtController;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author DELL
 */
public class DebtView extends javax.swing.JPanel {
    private DebtController debtController;
    /**
     * Creates new form DebtView
     */
    public DebtView() {
        initComponents();
        debtController=new DebtController(this);
        this.deshabilitarBotones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipalD = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDebts = new javax.swing.JTable(){
            public boolean isCellEditable(int i, int j){
                return false;
            }
        };
        btnMoverAgregar = new javax.swing.JButton();
        btnMoverActualizar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnUndo = new javax.swing.JButton();
        btnRedo = new javax.swing.JButton();
        panelAgregarD = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombreAgregar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtValorAgregar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNumCuotasAgregar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFechaInicialAgregar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbxPeriodicidadAgregar = new javax.swing.JComboBox<>();
        cbxCategoriaAgregar = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcionAgregar = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnRegresarAgregar = new javax.swing.JButton();
        panelActualizarD = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNombreActualizar = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtValorActualizar = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtNumCuotasActualizar = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtFechaInicialActualizar = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cbxPeriodicidadActualizar = new javax.swing.JComboBox<>();
        cbxCategoriaActualizar = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDescripcionActualizar = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        btnRegresarActualizar = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        setLayout(new java.awt.CardLayout());

        tableDebts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableDebts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDebtsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableDebts);

        btnMoverAgregar.setText("Agregar deuda");
        btnMoverAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoverAgregarActionPerformed(evt);
            }
        });

        btnMoverActualizar.setText("Actualizar");
        btnMoverActualizar.setActionCommand("");
        btnMoverActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoverActualizarActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DEUDAS");

        btnUndo.setEnabled(false);
        btnUndo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Arrows-Undo-icon.png"))); // NOI18N
        btnUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUndoActionPerformed(evt);
            }
        });

        btnRedo.setEnabled(false);
        btnRedo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Arrows-Redo-icon.png"))); // NOI18N
        btnRedo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalDLayout = new javax.swing.GroupLayout(panelPrincipalD);
        panelPrincipalD.setLayout(panelPrincipalDLayout);
        panelPrincipalDLayout.setHorizontalGroup(
            panelPrincipalDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalDLayout.createSequentialGroup()
                .addGroup(panelPrincipalDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalDLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalDLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnMoverAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnMoverActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(26, 26, 26)
                        .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(btnUndo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRedo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelPrincipalDLayout.setVerticalGroup(
            panelPrincipalDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalDLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalDLayout.createSequentialGroup()
                        .addGroup(panelPrincipalDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMoverAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMoverActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(44, 44, 44))
                    .addGroup(panelPrincipalDLayout.createSequentialGroup()
                        .addGroup(panelPrincipalDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUndo)
                            .addComponent(btnRedo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(panelPrincipalD, "card2");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Agregar deuda");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nombre");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Valor a pagar");

        txtValorAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorAgregarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Numero de cuotas");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Fecha inicial");

        txtFechaInicialAgregar.setText("AAAA-MM-DD");
        txtFechaInicialAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaInicialAgregarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Descripcion");

        cbxPeriodicidadAgregar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semanal", "Mensual", "Semestral", "Anual" }));
        cbxPeriodicidadAgregar.setSelectedIndex(1);

        cbxCategoriaAgregar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Categoria");

        txtDescripcionAgregar.setColumns(20);
        txtDescripcionAgregar.setRows(5);
        jScrollPane2.setViewportView(txtDescripcionAgregar);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Periodicidad");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnRegresarAgregar.setText("Cancelar");
        btnRegresarAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAgregarDLayout = new javax.swing.GroupLayout(panelAgregarD);
        panelAgregarD.setLayout(panelAgregarDLayout);
        panelAgregarDLayout.setHorizontalGroup(
            panelAgregarDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarDLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panelAgregarDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAgregarDLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAgregarDLayout.createSequentialGroup()
                        .addGroup(panelAgregarDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAgregarDLayout.createSequentialGroup()
                                .addGroup(panelAgregarDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombreAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(txtNumCuotasAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                .addGroup(panelAgregarDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtValorAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(cbxPeriodicidadAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(54, 54, 54)
                                .addGroup(panelAgregarDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFechaInicialAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxCategoriaAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))))
                        .addGap(36, 36, 36))))
            .addGroup(panelAgregarDLayout.createSequentialGroup()
                .addGroup(panelAgregarDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAgregarDLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAgregarDLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(btnAgregar)
                        .addGap(92, 92, 92)
                        .addComponent(btnRegresarAgregar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAgregarDLayout.setVerticalGroup(
            panelAgregarDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(panelAgregarDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelAgregarDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panelAgregarDLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtNombreAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAgregarDLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtValorAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelAgregarDLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFechaInicialAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelAgregarDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAgregarDLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumCuotasAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAgregarDLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxPeriodicidadAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAgregarDLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxCategoriaAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelAgregarDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnRegresarAgregar))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        add(panelAgregarD, "card3");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Actualizar deuda");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Nombre");

        txtNombreActualizar.setText("jTextField1");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Valor a pagar");

        txtValorActualizar.setText("jTextField1");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Numero de cuotas");

        txtNumCuotasActualizar.setText("jTextField1");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Fecha inicial");

        txtFechaInicialActualizar.setText("jTextField1");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Descripcion");

        cbxPeriodicidadActualizar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semanal", "Mensual", "Semestral", "Anual" }));
        cbxPeriodicidadActualizar.setSelectedIndex(1);
        cbxPeriodicidadActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPeriodicidadActualizarActionPerformed(evt);
            }
        });

        cbxCategoriaActualizar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Categoria");

        txtDescripcionActualizar.setColumns(20);
        txtDescripcionActualizar.setRows(5);
        jScrollPane3.setViewportView(txtDescripcionActualizar);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Periodicidad");

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnRegresarActualizar.setText("Cancelar");
        btnRegresarActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelActualizarDLayout = new javax.swing.GroupLayout(panelActualizarD);
        panelActualizarD.setLayout(panelActualizarDLayout);
        panelActualizarDLayout.setHorizontalGroup(
            panelActualizarDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActualizarDLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panelActualizarDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelActualizarDLayout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelActualizarDLayout.createSequentialGroup()
                        .addGroup(panelActualizarDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelActualizarDLayout.createSequentialGroup()
                                .addGroup(panelActualizarDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombreActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel13)
                                    .addComponent(txtNumCuotasActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                .addGroup(panelActualizarDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtValorActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)
                                    .addComponent(cbxPeriodicidadActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(54, 54, 54)
                                .addGroup(panelActualizarDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFechaInicialActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxCategoriaActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(36, 36, 36))))
            .addGroup(panelActualizarDLayout.createSequentialGroup()
                .addGroup(panelActualizarDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelActualizarDLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelActualizarDLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(btnActualizar)
                        .addGap(92, 92, 92)
                        .addComponent(btnRegresarActualizar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelActualizarDLayout.setVerticalGroup(
            panelActualizarDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActualizarDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(panelActualizarDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelActualizarDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panelActualizarDLayout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtNombreActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelActualizarDLayout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtValorActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelActualizarDLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFechaInicialActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelActualizarDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelActualizarDLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumCuotasActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelActualizarDLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxPeriodicidadActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelActualizarDLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxCategoriaActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelActualizarDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnRegresarActualizar))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        add(panelActualizarD, "card3");
    }// </editor-fold>//GEN-END:initComponents

    private void btnMoverAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoverAgregarActionPerformed
        debtController.MoveActionPerformed(evt);
    }//GEN-LAST:event_btnMoverAgregarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        this.btnUndo.setEnabled(true);
        debtController.MoveActionPerformed(evt);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        this.btnUndo.setEnabled(true);
        debtController.MoveActionPerformed(evt);
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnMoverActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoverActualizarActionPerformed
        debtController.MoveActionPerformed(evt);
    }//GEN-LAST:event_btnMoverActualizarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        this.btnUndo.setEnabled(true);
        debtController.MoveActionPerformed(evt);
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnRegresarActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActualizarActionPerformed
        debtController.MoveActionPerformed(evt);
    }//GEN-LAST:event_btnRegresarActualizarActionPerformed

    private void btnRegresarAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarAgregarActionPerformed
        debtController.MoveActionPerformed(evt);
    }//GEN-LAST:event_btnRegresarAgregarActionPerformed

    private void tableDebtsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDebtsMouseClicked
        debtController.TableMouseClicked(evt);
    }//GEN-LAST:event_tableDebtsMouseClicked

    private void cbxPeriodicidadActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPeriodicidadActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxPeriodicidadActualizarActionPerformed

    private void txtValorAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorAgregarActionPerformed

    private void txtFechaInicialAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaInicialAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaInicialAgregarActionPerformed

    private void btnUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUndoActionPerformed
        debtController.MoveActionPerformed(evt);
    }//GEN-LAST:event_btnUndoActionPerformed

    private void btnRedoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedoActionPerformed
        debtController.MoveActionPerformed(evt);
    }//GEN-LAST:event_btnRedoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnMoverActualizar;
    private javax.swing.JButton btnMoverAgregar;
    private javax.swing.JButton btnRedo;
    private javax.swing.JButton btnRegresarActualizar;
    private javax.swing.JButton btnRegresarAgregar;
    private javax.swing.JButton btnUndo;
    private javax.swing.JComboBox<String> cbxCategoriaActualizar;
    private javax.swing.JComboBox<String> cbxCategoriaAgregar;
    private javax.swing.JComboBox<String> cbxPeriodicidadActualizar;
    private javax.swing.JComboBox<String> cbxPeriodicidadAgregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panelActualizarD;
    private javax.swing.JPanel panelAgregarD;
    private javax.swing.JPanel panelPrincipalD;
    private javax.swing.JTable tableDebts;
    private javax.swing.JTextArea txtDescripcionActualizar;
    private javax.swing.JTextArea txtDescripcionAgregar;
    private javax.swing.JTextField txtFechaInicialActualizar;
    private javax.swing.JTextField txtFechaInicialAgregar;
    private javax.swing.JTextField txtNombreActualizar;
    private javax.swing.JTextField txtNombreAgregar;
    private javax.swing.JTextField txtNumCuotasActualizar;
    private javax.swing.JTextField txtNumCuotasAgregar;
    private javax.swing.JTextField txtValorActualizar;
    private javax.swing.JTextField txtValorAgregar;
    // End of variables declaration//GEN-END:variables
    public void cleanFieldsAgregar(){
        this.txtDescripcionAgregar.setText("");
        this.txtFechaInicialAgregar.setText("AAAA-MM-DD");
        this.txtNombreAgregar.setText("");
        this.txtNumCuotasAgregar.setText("");
        this.txtValorAgregar.setText("");
    }
    
    public void deshabilitarBotones(){
        this.btnBorrar.setEnabled(false);
        this.btnMoverActualizar.setEnabled(false);
    }
    
    public void habilitarBotones(){
        this.btnBorrar.setEnabled(true);
        this.btnMoverActualizar.setEnabled(true);
    }
    
    public void activarPanelAgregar(){
        this.panelPrincipalD.setVisible(false);
        this.panelAgregarD.setVisible(true);
        this.panelActualizarD.setVisible(false);
    }
    
    public void activarPanelActualizar(){
        this.panelPrincipalD.setVisible(false);
        this.panelAgregarD.setVisible(false);
        this.panelActualizarD.setVisible(true);
    }
    
    public void activarPanelPrincipalD(){
        this.panelPrincipalD.setVisible(true);
        this.panelAgregarD.setVisible(false);
        this.panelActualizarD.setVisible(false);
    }
    
    public JButton getBtnBorrar() {
        return btnBorrar;
    }

    public void setBtnBorrar(JButton btnBorrar) {
        this.btnBorrar = btnBorrar;
    }

    public JButton getBtnMoverActualizar() {
        return btnMoverActualizar;
    }

    public void setBtnMoverActualizar(JButton btnMoverActualizar) {
        this.btnMoverActualizar = btnMoverActualizar;
    }

    public JButton getBtnMoverAgregar() {
        return btnMoverAgregar;
    }

    public void setBtnMoverAgregar(JButton btnMoverAgregar) {
        this.btnMoverAgregar = btnMoverAgregar;
    }

    public JPanel getPanelActualizarD() {
        return panelActualizarD;
    }

    public void setPanelActualizarD(JPanel panelActualizarD) {
        this.panelActualizarD = panelActualizarD;
    }

    public JPanel getPanelAgregarD() {
        return panelAgregarD;
    }

    public void setPanelAgregarD(JPanel panelAgregarD) {
        this.panelAgregarD = panelAgregarD;
    }

    public JPanel getPanelPrincipalD() {
        return panelPrincipalD;
    }

    public void setPanelPrincipalD(JPanel panelPrincipalD) {
        this.panelPrincipalD = panelPrincipalD;
    }

    public JTable getTableDebts() {
        return tableDebts;
    }

    public void setTableDebts(JTable tableDebts) {
        this.tableDebts = tableDebts;
    }

    public JButton getBtnRegresarActualizar() {
        return btnRegresarActualizar;
    }

    public void setBtnRegresarActualizar(JButton btnRegresarActualizar) {
        this.btnRegresarActualizar = btnRegresarActualizar;
    }

    public JButton getBtnRegresarAgregar() {
        return btnRegresarAgregar;
    }

    public void setBtnRegresarAgregar(JButton btnRegresarAgregar) {
        this.btnRegresarAgregar = btnRegresarAgregar;
    }

    public DebtController getDebtController() {
        return debtController;
    }

    public void setDebtController(DebtController debtController) {
        this.debtController = debtController;
    }

    public JButton getBtnActualizar() {
        return btnActualizar;
    }

    public void setBtnActualizar(JButton btnActualizar) {
        this.btnActualizar = btnActualizar;
    }

    public JButton getBtnAgregar() {
        return btnAgregar;
    }

    public void setBtnAgregar(JButton btnAgregar) {
        this.btnAgregar = btnAgregar;
    }

    public JButton getBtnRedo() {
        return btnRedo;
    }

    public void setBtnRedo(JButton btnRedo) {
        this.btnRedo = btnRedo;
    }

    public JButton getBtnUndo() {
        return btnUndo;
    }

    public void setBtnUndo(JButton btnUndo) {
        this.btnUndo = btnUndo;
    }

    public JComboBox<String> getCbxCategoriaActualizar() {
        return cbxCategoriaActualizar;
    }

    public void setCbxCategoriaActualizar(JComboBox<String> cbxCategoriaActualizar) {
        this.cbxCategoriaActualizar = cbxCategoriaActualizar;
    }

    public JComboBox<String> getCbxCategoriaAgregar() {
        return cbxCategoriaAgregar;
    }

    public void setCbxCategoriaAgregar(JComboBox<String> cbxCategoriaAgregar) {
        this.cbxCategoriaAgregar = cbxCategoriaAgregar;
    }

    public JComboBox<String> getCbxPeriodicidadActualizar() {
        return cbxPeriodicidadActualizar;
    }

    public void setCbxPeriodicidadActualizar(JComboBox<String> cbxPeriodicidadActualizar) {
        this.cbxPeriodicidadActualizar = cbxPeriodicidadActualizar;
    }

    public JComboBox<String> getCbxPeriodicidadAgregar() {
        return cbxPeriodicidadAgregar;
    }

    public void setCbxPeriodicidadAgregar(JComboBox<String> cbxPeriodicidadAgregar) {
        this.cbxPeriodicidadAgregar = cbxPeriodicidadAgregar;
    }

    public JTextArea getTxtDescripcionActualizar() {
        return txtDescripcionActualizar;
    }

    public void setTxtDescripcionActualizar(JTextArea txtDescripcionActualizar) {
        this.txtDescripcionActualizar = txtDescripcionActualizar;
    }

    public JTextArea getTxtDescripcionAgregar() {
        return txtDescripcionAgregar;
    }

    public void setTxtDescripcionAgregar(JTextArea txtDescripcionAgregar) {
        this.txtDescripcionAgregar = txtDescripcionAgregar;
    }

    public JTextField getTxtFechaInicialActualizar() {
        return txtFechaInicialActualizar;
    }

    public void setTxtFechaInicialActualizar(JTextField txtFechaInicialActualizar) {
        this.txtFechaInicialActualizar = txtFechaInicialActualizar;
    }

    public JTextField getTxtFechaInicialAgregar() {
        return txtFechaInicialAgregar;
    }

    public void setTxtFechaInicialAgregar(JTextField txtFechaInicialAgregar) {
        this.txtFechaInicialAgregar = txtFechaInicialAgregar;
    }

    public JTextField getTxtNombreActualizar() {
        return txtNombreActualizar;
    }

    public void setTxtNombreActualizar(JTextField txtNombreActualizar) {
        this.txtNombreActualizar = txtNombreActualizar;
    }

    public JTextField getTxtNombreAgregar() {
        return txtNombreAgregar;
    }

    public void setTxtNombreAgregar(JTextField txtNombreAgregar) {
        this.txtNombreAgregar = txtNombreAgregar;
    }

    public JTextField getTxtNumCuotasActualizar() {
        return txtNumCuotasActualizar;
    }

    public void setTxtNumCuotasActualizar(JTextField txtNumCuotasActualizar) {
        this.txtNumCuotasActualizar = txtNumCuotasActualizar;
    }

    public JTextField getTxtNumCuotasAgregar() {
        return txtNumCuotasAgregar;
    }

    public void setTxtNumCuotasAgregar(JTextField txtNumCuotasAgregar) {
        this.txtNumCuotasAgregar = txtNumCuotasAgregar;
    }

    public JTextField getTxtValorActualizar() {
        return txtValorActualizar;
    }

    public void setTxtValorActualizar(JTextField txtValorActualizar) {
        this.txtValorActualizar = txtValorActualizar;
    }

    public JTextField getTxtValorAgregar() {
        return txtValorAgregar;
    }

    public void setTxtValorAgregar(JTextField txtValorAgregar) {
        this.txtValorAgregar = txtValorAgregar;
    }
    
    
    

    
}
