/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.MainController;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author DELL
 */
public class Main extends javax.swing.JFrame {
    private MainController mainController;
    /**
     * Creates new form Menu
     */
    public Main() {
        initComponents();
        mainController = new MainController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        panelBotones = new javax.swing.JPanel();
        btnEventos = new javax.swing.JButton();
        btnDeudas = new javax.swing.JButton();
        btnCategorias = new javax.swing.JButton();
        panelDerecho = new javax.swing.JPanel();
        panelInfo = new javax.swing.JPanel();
        lblText1 = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        lblNombreCont = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        lblValorCont = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblFechaCont = new javax.swing.JLabel();
        btnSi = new javax.swing.JButton();
        lblCuota = new javax.swing.JLabel();
        lblCuotaCont = new javax.swing.JLabel();
        debtView = new view.DebtView();
        eventView = new view.EventView();
        categoryView = new view.CategoryView();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tu App de confianza $_$");
        setResizable(false);

        panelBotones.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        panelBotones.setPreferredSize(new java.awt.Dimension(294, 317));

        btnEventos.setText("Eventos proximos");
        btnEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEventosActionPerformed(evt);
            }
        });

        btnDeudas.setText("Tus deudas");
        btnDeudas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeudasActionPerformed(evt);
            }
        });

        btnCategorias.setText("Categorias");
        btnCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDeudas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEventos, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(btnCategorias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnEventos, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnDeudas, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(btnCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        panelDerecho.setPreferredSize(new java.awt.Dimension(588, 317));
        panelDerecho.setLayout(new java.awt.CardLayout());

        panelInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblText1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblText1.setText("¿Quieres ver tu proximo pago?");

        btnSiguiente.setText("Siguiente");
        btnSiguiente.setVisible(false);
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        lblNombre.setVisible(false);
        lblNombre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNombre.setText("Nombre:");

        lblNombreCont.setVisible(false);
        lblNombreCont.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNombreCont.setText("jLabel3");

        lblValor.setVisible(false);
        lblValor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblValor.setText("Valor:");

        lblValorCont.setVisible(false);
        lblValorCont.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblValorCont.setText("jLabel5");

        lblFecha.setVisible(false);
        lblFecha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblFecha.setText("Fecha:");

        lblFechaCont.setVisible(false);
        lblFechaCont.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFechaCont.setText("jLabel5");

        btnSi.setText("Sí");
        btnSi.setActionCommand("Si");
        btnSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiActionPerformed(evt);
            }
        });

        lblCuota.setVisible(false);
        lblCuota.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCuota.setText("Cuota:");

        lblCuotaCont.setVisible(false);
        lblCuotaCont.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCuotaCont.setText("jLabel2");

        javax.swing.GroupLayout panelInfoLayout = new javax.swing.GroupLayout(panelInfo);
        panelInfo.setLayout(panelInfoLayout);
        panelInfoLayout.setHorizontalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblText1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelInfoLayout.createSequentialGroup()
                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNombre)
                            .addComponent(lblValor)
                            .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblCuota)
                                .addComponent(lblFecha)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelInfoLayout.createSequentialGroup()
                                .addComponent(lblCuotaCont)
                                .addGap(326, 326, 326))
                            .addGroup(panelInfoLayout.createSequentialGroup()
                                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFechaCont, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblValorCont, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblNombreCont, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSi, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(201, 201, 201))
        );
        panelInfoLayout.setVerticalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblText1)
                .addGap(18, 18, 18)
                .addComponent(btnSi, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(lblNombreCont))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInfoLayout.createSequentialGroup()
                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblValorCont)
                            .addComponent(lblValor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFecha)
                            .addComponent(lblFechaCont)))
                    .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCuota)
                    .addComponent(lblCuotaCont))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        panelDerecho.add(panelInfo, "card2");
        panelDerecho.add(debtView, "card3");
        panelDerecho.add(eventView, "card4");
        panelDerecho.add(categoryView, "card5");

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDerecho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelDerecho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEventosActionPerformed
        mainController.actionPerformed(evt);
    }//GEN-LAST:event_btnEventosActionPerformed

    private void btnCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriasActionPerformed
        mainController.actionPerformed(evt);
    }//GEN-LAST:event_btnCategoriasActionPerformed

    private void btnDeudasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeudasActionPerformed
       mainController.actionPerformed(evt);
    }//GEN-LAST:event_btnDeudasActionPerformed

    private void btnSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSiActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSiguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCategorias;
    private javax.swing.JButton btnDeudas;
    private javax.swing.JButton btnEventos;
    private javax.swing.JButton btnSi;
    private javax.swing.JButton btnSiguiente;
    private view.CategoryView categoryView;
    private view.DebtView debtView;
    private view.EventView eventView;
    private javax.swing.JLabel lblCuota;
    private javax.swing.JLabel lblCuotaCont;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFechaCont;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreCont;
    private javax.swing.JLabel lblText1;
    private javax.swing.JLabel lblValor;
    private javax.swing.JLabel lblValorCont;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelDerecho;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables
    
    public void cambiarADebt(){
        panelInfo.setVisible(false);
        debtView.setVisible(true);
        eventView.setVisible(false);
        categoryView.setVisible(false);
    }
    
    public void cambiarAEvent(){
        panelInfo.setVisible(false);
        debtView.setVisible(false);
        eventView.setVisible(true);
        categoryView.setVisible(false);
    }
    
    public void cambiarACategory(){
        panelInfo.setVisible(false);
        debtView.setVisible(false);
        eventView.setVisible(false);
        categoryView.setVisible(true);
    }
    
    public JButton getBtnCategorias() {
        return btnCategorias;
    }

    public void setBtnCategorias(JButton btnCategorias) {
        this.btnCategorias = btnCategorias;
    }

    public JButton getBtnDeudas() {
        return btnDeudas;
    }

    public void setBtnDeudas(JButton btnDeudas) {
        this.btnDeudas = btnDeudas;
    }

    public JButton getBtnEventos() {
        return btnEventos;
    }

    public void setBtnEventos(JButton btnEventos) {
        this.btnEventos = btnEventos;
    }

    public JButton getBtnSi() {
        return btnSi;
    }

    public void setBtnSi(JButton btnSi) {
        this.btnSi = btnSi;
    }

    public JButton getBtnSiguiente() {
        return btnSiguiente;
    }

    public void setBtnSiguiente(JButton btnSiguiente) {
        this.btnSiguiente = btnSiguiente;
    }

    public JLabel getLblCuota() {
        return lblCuota;
    }

    public void setLblCuota(JLabel lblCuota) {
        this.lblCuota = lblCuota;
    }

    public JLabel getLblCuotaCont() {
        return lblCuotaCont;
    }

    public void setLblCuotaCont(JLabel lblCuotaCont) {
        this.lblCuotaCont = lblCuotaCont;
    }

    public JLabel getLblFecha() {
        return lblFecha;
    }

    public void setLblFecha(JLabel lblFecha) {
        this.lblFecha = lblFecha;
    }

    public JLabel getLblFechaCont() {
        return lblFechaCont;
    }

    public void setLblFechaCont(JLabel lblFechaCont) {
        this.lblFechaCont = lblFechaCont;
    }

    public JLabel getLblNombre() {
        return lblNombre;
    }

    public void setLblNombre(JLabel lblNombre) {
        this.lblNombre = lblNombre;
    }

    public JLabel getLblNombreCont() {
        return lblNombreCont;
    }

    public void setLblNombreCont(JLabel lblNombreCont) {
        this.lblNombreCont = lblNombreCont;
    }

    public JLabel getLblText1() {
        return lblText1;
    }

    public void setLblText1(JLabel lblText1) {
        this.lblText1 = lblText1;
    }

    public JLabel getLblValor() {
        return lblValor;
    }

    public void setLblValor(JLabel lblValor) {
        this.lblValor = lblValor;
    }

    public JLabel getLblValorCont() {
        return lblValorCont;
    }

    public void setLblValorCont(JLabel lblValorCont) {
        this.lblValorCont = lblValorCont;
    }

    public JPanel getPanelBotones() {
        return panelBotones;
    }

    public void setPanelBotones(JPanel panelBotones) {
        this.panelBotones = panelBotones;
    }

    public JPanel getPanelInfo() {
        return panelInfo;
    }

    public void setPanelInfo(JPanel panelInfo) {
        this.panelInfo=panelInfo;
    }

    public JPanel getPanelMenu() {
        return panelMenu;
    }

    public void setPanelMenu(JPanel panelMenu) {
        this.panelMenu = panelMenu;
    }

    

    
}
