/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.DebtController;
import controller.EventController;
import controller.MainController;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author DELL
 */
public class Main extends javax.swing.JFrame {
    private MainController mainController;
    /**
     * Creates new form Menu
     */
    public Main() {
        initComponents();
        mainController = new MainController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        panelBotones = new javax.swing.JPanel();
        btnEventos = new javax.swing.JButton();
        btnDeudas = new javax.swing.JButton();
        btnCategorias = new javax.swing.JButton();
        panelDerecho = new javax.swing.JPanel();
        panelPregunta = new javax.swing.JPanel();
        lblPregunta = new javax.swing.JLabel();
        btnSi = new javax.swing.JButton();
        lblNoHayEventos = new javax.swing.JLabel();
        panelInfo = new javax.swing.JPanel();
        lblCuotaCont = new javax.swing.JLabel();
        lblCuota = new javax.swing.JLabel();
        lblFechaCont = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblValorCont = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        lblNombreCont = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        btnPagado = new javax.swing.JButton();
        lblAvance = new javax.swing.JLabel();
        debtView = new view.DebtView();
        eventView = new view.EventView();
        categoryView = new view.CategoryView();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tu App de confianza $_$");
        setResizable(false);

        panelBotones.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        panelBotones.setPreferredSize(new java.awt.Dimension(294, 317));

        btnEventos.setText("Eventos proximos");
        btnEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEventosActionPerformed(evt);
            }
        });

        btnDeudas.setText("Tus deudas");
        btnDeudas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeudasActionPerformed(evt);
            }
        });

        btnCategorias.setText("Categorias");
        btnCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDeudas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEventos, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(btnCategorias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnEventos, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnDeudas, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        panelDerecho.setPreferredSize(new java.awt.Dimension(588, 317));
        panelDerecho.setLayout(new java.awt.CardLayout());

        panelPregunta.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblPregunta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPregunta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPregunta.setText("¿Quieres ver tu proximo pago?");

        btnSi.setText("Sí");
        btnSi.setActionCommand("Si");
        btnSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiActionPerformed(evt);
            }
        });

        lblNoHayEventos.setVisible(false);
        lblNoHayEventos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNoHayEventos.setForeground(new java.awt.Color(255, 0, 0));
        lblNoHayEventos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNoHayEventos.setText("jLabel1");

        javax.swing.GroupLayout panelPreguntaLayout = new javax.swing.GroupLayout(panelPregunta);
        panelPregunta.setLayout(panelPreguntaLayout);
        panelPreguntaLayout.setHorizontalGroup(
            panelPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPreguntaLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblPregunta, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPreguntaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSi, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(208, 208, 208))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPreguntaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNoHayEventos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelPreguntaLayout.setVerticalGroup(
            panelPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPreguntaLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblPregunta)
                .addGap(36, 36, 36)
                .addComponent(btnSi, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(lblNoHayEventos)
                .addGap(70, 70, 70))
        );

        panelDerecho.add(panelPregunta, "card2");

        panelInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblCuotaCont.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCuotaCont.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCuotaCont.setText("jLabel2");

        lblCuota.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCuota.setText("Cuota:");

        lblFechaCont.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFechaCont.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFechaCont.setText("jLabel5");

        lblFecha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblFecha.setText("Fecha:");

        lblValorCont.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblValorCont.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValorCont.setText("jLabel5");

        lblValor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblValor.setText("Valor:");

        lblNombreCont.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNombreCont.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreCont.setText("jLabel3");

        lblNombre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNombre.setText("Nombre:");

        btnPagado.setText("Fraccionamiento pagado");
        btnPagado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagadoActionPerformed(evt);
            }
        });

        lblAvance.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAvance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAvance.setText("jLabel1");

        javax.swing.GroupLayout panelInfoLayout = new javax.swing.GroupLayout(panelInfo);
        panelInfo.setLayout(panelInfoLayout);
        panelInfoLayout.setHorizontalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInfoLayout.createSequentialGroup()
                        .addGap(0, 197, Short.MAX_VALUE)
                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoLayout.createSequentialGroup()
                                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblNombre)
                                    .addComponent(lblValor)
                                    .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblCuota)
                                        .addComponent(lblFecha)))
                                .addGap(41, 41, 41)
                                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblCuotaCont)
                                    .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblFechaCont, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblValorCont, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblNombreCont, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addGap(201, 201, 201))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoLayout.createSequentialGroup()
                                .addComponent(btnPagado, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(190, 190, 190))))
                    .addComponent(lblAvance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panelInfoLayout.setVerticalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblAvance)
                .addGap(28, 28, 28)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInfoLayout.createSequentialGroup()
                        .addComponent(lblNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblValor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCuota))
                    .addGroup(panelInfoLayout.createSequentialGroup()
                        .addComponent(lblNombreCont)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblValorCont)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFechaCont)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCuotaCont)))
                .addGap(35, 35, 35)
                .addComponent(btnPagado, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        panelDerecho.add(panelInfo, "card6");
        panelDerecho.add(debtView, "card3");
        panelDerecho.add(eventView, "card4");
        panelDerecho.add(categoryView, "card5");

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDerecho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelDerecho, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                    .addComponent(panelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEventosActionPerformed
        mainController.actionPerformed(evt);
        EventController.showEvent();
        EventController.startComponentsDeuda();
    }//GEN-LAST:event_btnEventosActionPerformed

    private void btnCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriasActionPerformed
        mainController.actionPerformed(evt);
    }//GEN-LAST:event_btnCategoriasActionPerformed

    private void btnDeudasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeudasActionPerformed
       mainController.actionPerformed(evt);
       DebtController.showDebt();
    }//GEN-LAST:event_btnDeudasActionPerformed

    private void btnSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiActionPerformed
        mainController.actionPerformed(evt);
    }//GEN-LAST:event_btnSiActionPerformed

    private void btnPagadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagadoActionPerformed
        mainController.actionPerformed(evt);
    }//GEN-LAST:event_btnPagadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCategorias;
    private javax.swing.JButton btnDeudas;
    private javax.swing.JButton btnEventos;
    private javax.swing.JButton btnPagado;
    private javax.swing.JButton btnSi;
    private view.CategoryView categoryView;
    private view.DebtView debtView;
    private view.EventView eventView;
    private javax.swing.JLabel lblAvance;
    private javax.swing.JLabel lblCuota;
    private javax.swing.JLabel lblCuotaCont;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFechaCont;
    private javax.swing.JLabel lblNoHayEventos;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreCont;
    private javax.swing.JLabel lblPregunta;
    private javax.swing.JLabel lblValor;
    private javax.swing.JLabel lblValorCont;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelDerecho;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelPregunta;
    // End of variables declaration//GEN-END:variables
    
    public void cambiarADebt(){
        panelPregunta.setVisible(false);
        debtView.setVisible(true);
        eventView.setVisible(false);
        categoryView.setVisible(false);
        panelInfo.setVisible(false);
    }
    
    public void cambiarAEvent(){
        panelPregunta.setVisible(false);
        debtView.setVisible(false);
        eventView.setVisible(true);
        categoryView.setVisible(false);
        panelInfo.setVisible(false);
    }
    
    public void cambiarACategory(){
        panelPregunta.setVisible(false);
        debtView.setVisible(false);
        eventView.setVisible(false);
        categoryView.setVisible(true);
        panelInfo.setVisible(false);
    }
    
    public void cambiarAInfo(){
        panelPregunta.setVisible(false);
        debtView.setVisible(false);
        eventView.setVisible(false);
        categoryView.setVisible(false);
        panelInfo.setVisible(true);
    }
    
    public void cambiarAPregunta(){
        panelPregunta.setVisible(true);
        debtView.setVisible(false);
        eventView.setVisible(false);
        categoryView.setVisible(false);
        panelInfo.setVisible(false);
        this.lblNoHayEventos.setVisible(true);
        this.lblPregunta.setVisible(false);
        this.btnSi.setVisible(false);
        this.lblNoHayEventos.setText("¡Felicitaciones! no tiene fraccionamientos pendientes");
    }
    
    public JButton getBtnCategorias() {
        return btnCategorias;
    }

    public void setBtnCategorias(JButton btnCategorias) {
        this.btnCategorias = btnCategorias;
    }

    public JButton getBtnDeudas() {
        return btnDeudas;
    }

    public void setBtnDeudas(JButton btnDeudas) {
        this.btnDeudas = btnDeudas;
    }

    public JButton getBtnEventos() {
        return btnEventos;
    }

    public void setBtnEventos(JButton btnEventos) {
        this.btnEventos = btnEventos;
    }

    public JButton getBtnSi() {
        return btnSi;
    }

    public void setBtnSi(JButton btnSi) {
        this.btnSi = btnSi;
    }

    public JButton getBtnSiguiente() {
        return btnPagado;
    }

    public void setBtnSiguiente(JButton btnSiguiente) {
        this.btnPagado = btnSiguiente;
    }

    public JLabel getLblCuota() {
        return lblCuota;
    }

    public void setLblCuota(JLabel lblCuota) {
        this.lblCuota = lblCuota;
    }

    public JLabel getLblCuotaCont() {
        return lblCuotaCont;
    }

    public void setLblCuotaCont(JLabel lblCuotaCont) {
        this.lblCuotaCont = lblCuotaCont;
    }

    public JLabel getLblFecha() {
        return lblFecha;
    }

    public void setLblFecha(JLabel lblFecha) {
        this.lblFecha = lblFecha;
    }

    public JLabel getLblFechaCont() {
        return lblFechaCont;
    }

    public void setLblFechaCont(JLabel lblFechaCont) {
        this.lblFechaCont = lblFechaCont;
    }

    public JLabel getLblNombre() {
        return lblNombre;
    }

    public void setLblNombre(JLabel lblNombre) {
        this.lblNombre = lblNombre;
    }

    public JLabel getLblNombreCont() {
        return lblNombreCont;
    }

    public void setLblNombreCont(JLabel lblNombreCont) {
        this.lblNombreCont = lblNombreCont;
    }

    public JLabel getLblText1() {
        return lblPregunta;
    }

    public void setLblText1(JLabel lblText1) {
        this.lblPregunta = lblText1;
    }

    public JLabel getLblValor() {
        return lblValor;
    }

    public void setLblValor(JLabel lblValor) {
        this.lblValor = lblValor;
    }

    public JLabel getLblValorCont() {
        return lblValorCont;
    }

    public void setLblValorCont(JLabel lblValorCont) {
        this.lblValorCont = lblValorCont;
    }

    public JPanel getPanelBotones() {
        return panelBotones;
    }

    public void setPanelBotones(JPanel panelBotones) {
        this.panelBotones = panelBotones;
    }

    public JPanel getPanelMenu() {
        return panelMenu;
    }

    public void setPanelMenu(JPanel panelMenu) {
        this.panelMenu = panelMenu;
    }

    public MainController getMainController() {
        return mainController;
    }

    public void setMainController(MainController mainController) {
        this.mainController = mainController;
    }

    public CategoryView getCategoryView() {
        return categoryView;
    }

    public void setCategoryView(CategoryView categoryView) {
        this.categoryView = categoryView;
    }

    public DebtView getDebtView() {
        return debtView;
    }

    public void setDebtView(DebtView debtView) {
        this.debtView = debtView;
    }

    public EventView getEventView() {
        return eventView;
    }

    public void setEventView(EventView eventView) {
        this.eventView = eventView;
    }

    public JPanel getPanelDerecho() {
        return panelDerecho;
    }

    public void setPanelDerecho(JPanel panelDerecho) {
        this.panelDerecho = panelDerecho;
    }

    public JPanel getPanelInfo() {
        return panelInfo;
    }

    public void setPanelInfo(JPanel panelInfo) {
        this.panelInfo = panelInfo;
    }

    public JPanel getPanelPregunta() {
        return panelPregunta;
    }

    public void setPanelPregunta(JPanel panelPregunta) {
        this.panelPregunta = panelPregunta;
    }

    public JButton getBtnPagado() {
        return btnPagado;
    }

    public void setBtnPagado(JButton btnPagado) {
        this.btnPagado = btnPagado;
    }

    public JLabel getLblAvance() {
        return lblAvance;
    }

    public void setLblAvance(JLabel lblAvance) {
        this.lblAvance = lblAvance;
    }

    public JLabel getLblPregunta() {
        return lblPregunta;
    }

    public void setLblPregunta(JLabel lblPregunta) {
        this.lblPregunta = lblPregunta;
    }

    public JLabel getLblNoHayEventos() {
        return lblNoHayEventos;
    }

    public void setLblNoHayEventos(JLabel lblNoHayEventos) {
        this.lblNoHayEventos = lblNoHayEventos;
    }

}
